### ISSUE TITLE
Add support for test_spec Specification DSL attribute

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/Core#129]
To implement this issue:

- Add the `test_spec` DSL attribute invoking the `subspec` one.
- Add an instance property to the `Specification` class: `test_specification?` (or something similar).
- Exclude this specification from the inherited dependencies.

--

via @supermarin

**Comment by segiddins** [comment]
Since there doesn't seem to be interest from anyone to actually implement this, I think we ought to close the issue.

**Comment by orta** [comment]
Aye, I tried this, turned out to be way more complicated than expected, happy to have it closed.
