### ISSUE TITLE
Allow to skip the installation of any dependency

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/Core#150]
The podfile should support the following syntax:

```ruby
skip 'Pod'
skip 'Pod/Subspec'
```

This feature is traversal to any block discussion. Moreover it is a cleaner and more general solution to #40.

**Comment by tomaskraina** [comment]
Any progress on this one?

**Comment by segiddins** [comment]
IMHO the proper fix to this is to have a `test_dependency` or something like that, which only adds header / framework search paths, instead of linking that dep to the pod itself.

**Comment by segiddins** [comment]
Closing as infeasible, but a PR with a proposal would be considered.
