### ISSUE TITLE
`pod lib lint` cannot find a dependency that is not on the master repo

### ISSUE THREAD

**Issue by fcy** [CocoaPods/Core#189]
If I've a pod that depends on another pod that is not available on the master repo `pod lib lint` fails with a message that it can't find the private pod. I've made a test project that I used to reproduce, you can download it [here](https://dl.dropboxusercontent.com/u/2702446/test-pod-lib-lint.zip), it contains a PrivateSpecs git repo with a podspec that I just changed the name from a public one and a pod called TestLint that depends on it.

Steps to reproduce:
1. Create a pod with `pod lib create TestLint`
2. Create or use a private specs repo, I used a local one but this happens in my company's "real" private repo as well
3. Add a private pod to it
4. Add the repo: `pod repo add test file:///Users/felipe/Documents/Projects/test-pod-lib-lint/PrivateSpecs/.git`
5. Edit `TestLint.podspec` and a dependency to the private pod: `s.dependency 'FCYAsserts+PrivateThing'`
6. Execute `pod lib lint` and you'll get this error: 

```
$ pod lib lint

[!] Unable to find a specification for `FCYAsserts+PrivateThing` depended upon by TestLint (0.1.0).
```

`pod lib lint` can find anything that is not on the master repo.

I've this problem since I installed 0.34.2, I don't know if it existed on 0.34.1.

**Comment by alexlee002** [comment]
I got a similar question:
