### ISSUE TITLE
use_frameworks Compile Issues

### ISSUE THREAD

**Issue by fabb** [CocoaPods/Core#222]
I have a mixed Objective-C/Swift project and activated `use_frameworks!` for the unit test target only. The unit test target does not compile though, when one of the test classes #imports a header from the app target, and that header #imports a header from a pod that is only activated for the app target. Without `use_frameworks!` it works fine.

I used cocoapods 0.36.0.rc.1

Example project: https://github.com/fabb/UseFrameworksTest

**Comment by fabb** [comment]
cc @fabiopelosin

**Comment by segiddins** [comment]
This belongs on CocoaPods/CocoaPods.

**Comment by fabb** [comment]
Recreated issue in CocoaPods/CocoaPods: https://github.com/CocoaPods/CocoaPods/issues/3338
