### ISSUE TITLE
Use binary and source distribution in subspecs

### ISSUE THREAD

**Issue by lukasspiess** [CocoaPods/Core#227]
I think I might be trying to do something a little unconventional with my podspec.
The goal is to have two subspecs within one podspec file, of which one integrates our library as a compiled binary and the other as normal source code and have one of these subpecs set as a `default_subspec`
Initially, I expected to be able to specify the source variables per subspec but learned that apparently this is a global value throughout the whole podspec.
Do you have an idea about how this could be done? I'd like to avoid having framework and source code in one repository, if at all possible. Thanks!

**Comment by neonichu** [comment]
My recommendation would be to create two different specs for this use case. You can even utilise <https://github.com/CocoaPods/cocoapods-packager> to build the compiled binary and its podspec automatically.

**Comment by lukasspiess** [comment]
That's what I feared :)
Thanks for the info, didn't know about cocoapods-packager!
