### ISSUE TITLE
Podfile: Fuzzy operator '~>' doesn't install higher versions

### ISSUE THREAD

**Issue by poetmountain** [CocoaPods/Core#229]
Listing `pod 'AFNetworking', '~> 2.5.1'` in a Podfile should install 2.5.2 when `pod install` is run; however, 2.5.1 is always installed. The documentation claims that any version < 2.6.0 should be installed in this case. This is using cocoapods 0.36.1.

**Comment by kylef** [comment]
That's not correct, when running `pod install`. The version will be locked to the version in `Podfile.lock`. You want to use `pod update` if you want to update the pod to the latest version that meets the requirements.

```shell
$ pod update AFNetworking
```

**Comment by poetmountain** [comment]
Why would `pod install` not pick up version updates if defined in the Podfile? So if you made a change to the Podfile, you'd have to run both `install` and `update` to get up-to-date. `pod install` should really be doing both, because '~> 2.5.1' is just a starting point.

**Comment by kylef** [comment]
There is a lock file (`Podfile.lock`) which ensures that if you run `pod install` multiple times (and on different machines) you will get **exactly** the same dependencies and versions every time. So, you can run `pod install` on your machine, a co-worker can run `pod install` on another machine and you will both have exactly the same version of dependencies. This means that if a dependency releases an update it won't just break your code-base, you have to explicitly update to that version via `pod update`.
