### ISSUE TITLE
Typo in CHANGELOG

### ISSUE THREAD

**Issue by wjk** [CocoaPods/Core#237]
I just noticed a typo in your [`CHANGELOG.md`](https://github.com/CocoaPods/Core/blob/master/CHANGELOG.md). The #218 link points to a 404 page, as "[CocoaPods/Core](https://github.com/CocoaPods/Core)" was misspelled as "CocoaPods/**Coore**".

**Comment by segiddins** [comment]
@wjk I'd love a PR that fixes it!

**Comment by orta** [comment]
:+1:
