### ISSUE TITLE
Allow to specify additional build settings per dependency in the Podfile

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/Core#243]
Short-hand form:
```ruby
pod 'AFNetworking', :xcconfig => { 'GCC_PREPROCESSOR_DEFINITIONS' => %w($(inherited) AF_APP_EXTENSIONS=1) }
```

Expanded form:
```ruby
pod 'AFNetworking' do
  # Same as above
  settings['GCC_PREPROCESSOR_DEFINITIONS'] = %w($(inherited) AF_APP_EXTENSIONS=1)
  # or with syntax sugar:
  settings.gcc_preprocessor_definitions += 'AF_APP_EXTENSIONS=1'

  # Additional configuration-specific build setting
  config[:debug].settings['GCC_PREPROCESSOR_DEFINITIONS'] = 'DEBUG=1'

  # There could be conflicts with the podspec, sometimes it could be
  # needed to overwrite certain build settings.
  settings.ignore_conflicts!
end
```

Further thoughts:
* We should make plural build settings auto-inheriting
* We should warn when build settings from the podspec are overridden with different values and conflicting, but allow to 
* We could also allow some kind of syntax sugar to have short-hand definitions for the most commonly used build settings like `GCC_PREPROCESSOR_DEFINITIONS`.

/c @AliSoftware

**Comment by orta** [comment]
This is around trying to reduce the need for a Podfile, `post_install`

**Comment by AliSoftware** [comment]
:+1:

I'd probably use the same attribute names for short-hand and expanded syntaxes (i.e. `xcconfig['GCC_PREPROCESSOR_DEFINITIONS']` instead of `settings[…]`)

`defines = x` could be a short-hand for `xcconfig['GCC_PREPROCESSOR_DEFINITIONS'] = x`

Also \ref CocoaPods/CocoaPods#840

**Comment by mrackwitz** [comment]
@AliSoftware:

1. Yes, I saw that too, but then it gets confusing with subscripting for a specific configuration (`xcconfig`, `config`), which still doesn't fully convince me as it's in conflict how we allow to specify configuration-specific pods.
2. If the short-hand gets confusing, it hurts more than it helps.

**Comment by neonichu** [comment]
This whole feature has a lot of potential for confusion - especially with implicit behaviour, like automatic inheritance or simply overwriting settings from the podspec. I don't think it is a good idea to introduce a DSL for breaking Pods.

**Comment by AliSoftware** [comment]
@neonichu I get that providing too much convenient and short-hand versions to break a pod may be confusing, be the rationale is that:

* it's needed for injecting Preprocessor Definitions in a pod, which multiple pods like AFNetworking or MagicalRecord requires
  * AFNetworking requires `AF_APP_EXTENSIONS` to be usable in a WatchApp or Extension
  * MagicalRecord required `MR_ACTIVE_RECORD_LOGGING=0` to disable verbose mode until v2.3)
  * Probably more pods require that too
* Even if we don't provide this, people do it anyway (because they need), but they do it with a painful `post_install` script like this below.

```
post_install do |installer|
    puts "Post-Install: Enabling AFN in Extensions..."
    afn_targets = installer.project.targets.select { |target| target.name =~ /-AFNetworking$/ }
    afn_targets.each do |target|
        target.build_configurations.each do |config|
            old_defines = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || []
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = old_defines + ['AF_APP_EXTENSIONS=1']
        end
    end
end
```

Also @orta pointed out that `post_install` is massively/mainly used simply to inject `GCC_PREPROCESSOR_DEFINITIONS` to a pod, so having a nicer way to do that when it's actually needed seems a good idea (especially because the `post_install` way needs way more LOC to write in every `Podfile`)

So maybe we can simply keep the short form (e.g. `pod 'AFNetworking', :preprocessor_definitions => [AF_APP_EXTENSIONS]` or similar) as it's the most common use case, and abandon the expanded version?

**Comment by segiddins** [comment]
I believe AFNetworking just killed off `AF_APP_EXTENSIONS`, but I might be wrong

**Comment by segiddins** [comment]
I think this is a massive over-complication... I'd prefer we add a helper or two to the `Installer` to make using a post-install hook easier.

**Comment by AliSoftware** [comment]
I'm ok with providing helpers on `installer`.

The syntax could being something like this:

```ruby
post_install do |installer|
    installer.pod_targets('AFNetworking').add_define('AF_APP_EXTENSIONS=1', 'LOGS=1')
end
```
or
```ruby
post_install do |installer|
    installer.pod_targets('AFNetworking') do |target|
        target.add_define('AF_APP_EXTENSIONS=1', 'LOGS=1')
    end
end
```

**Comment by alloy** [comment]
> I think this is a massive over-complication... I'd prefer we add a helper or two to the Installer to make using a post-install hook easier.

:+1:

**Comment by segiddins** [comment]
Closing since it appears we agreed to go a different route. I'd be happy to wrap the installer that's passed to the hooks in a proxy with helper methods, though, if anyone wants to make a well-tested PR for that to CocoaPods/CocoaPods!

**Comment by tirrorex** [comment]
So it is not possible to add flags for a pod inherited from the main project instead of cocoapods?
There is absolutly no documentation about it and from the look of this issue you guys don't want it to be possible

**Comment by joshbernfeld** [comment]
What was the solution for this?

**Comment by danielpetroianu** [comment]
For anyone that keeps changing the build settings on the pods, maybe this can help:

I've wrote this script https://gist.github.com/danielpetroianu/ba99d85e399af0d930a056aa9dae551b and have been using it for 2+ yeas now
