### ISSUE TITLE
Can I use 0.35.0 and 0.38.2 simultaneously?

### ISSUE THREAD

**Issue by feefly1987** [CocoaPods/Core#268]
Due to the project, I want to use Cocoapods 0.35.0 and 0.38.2 simultaneously. Is there a solution to install two versions of Cocoapods and switch the current version by using command line?

**Comment by segiddins** [comment]
Yes, ruby gems has native support for installing multiple versions

**Comment by feefly1987** [comment]
Thanks!
Could you tell me how to switch the version?

**Comment by segiddins** [comment]
`pod _0.35.0_ install`, `pod _0.38.2_ install`
