### ISSUE TITLE
Remove `docset_url` from Specification DSL

### ISSUE THREAD

**Issue by orta** [CocoaPods/Core#284]
We have a DSL attribute that is used by ~10 pods, really, we should remove it to keep the DSL as small as possible. This likely came from before CocoaDocs existed.

**Comment by orta** [comment]
@CocoaPods/core opinions?

**Comment by neonichu** [comment]
Did a quick grep, it is used by 22 Pods as far as I can see, so I'm :+1: on it

**Comment by manuyavuz** [comment]
Very reasonable regarding we have CocoaDocs. :+1:

**Comment by segiddins** [comment]
👍🏻

**Comment by k0nserv** [comment]
:+1:
