### ISSUE TITLE
DSL directive `project` instead of `xcodeproj`

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/Core#298]
* The directive to specify a project is called `xcodeproj`.
* The directive to specify a workspace is called `workspace`.
* The construct to declare a target is called `target`.

But all those are based on artifacts created with or for Xcode. I think that's one of the most counter-intuitive things in the current DSL. I'd love when we could fix that, before we "finalize" the DSL for 1.0.

**Comment by orta** [comment]
I'm :+1: with this, makes sense. As long as we let people know about the change when running `pod install`
