### ISSUE TITLE
`A framework should only be specified by its name` linter error

### ISSUE THREAD

**Issue by sgl0v** [CocoaPods/Core#336]
There is a `dot` character in the framework's name, that I use in my application. Thus I get the next error while running `pod install`:

```
[!] The `SomePod` pod failed to validate due to 1 error:
    - ERROR | frameworks: A framework should only be specified by its name
```

According to the [linter implementation](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/linter.rb) the next regex is used to get invalid framework names: `/[^\w\-\+]/`. I'd propose to check whether or not the framework name has `.framework` suffix.

**Comment by segiddins** [comment]
I don't believe you can import a framework with a dot in its name?

**Comment by orta** [comment]
Yeah, I think you can only have a-Z and underscores in a clang module name, though shouldn't we be converting the dot to and underscore?
