### ISSUE TITLE
[Question] How to specify the CONFIGURATION_BUILD_DIR for a framework project

### ISSUE THREAD

**Issue by galenlin** [CocoaPods/Core#347]
I'm working on [Small](https://github.com/wequick/Small) and using CocoaPods for people to integrate with my framework.

While I specify:

``` ruby
s.vendored_framework = "Small.framework"
```

in [Small.podspec](https://github.com/wequick/Small/blob/master/Small.podspec)

**Pods** will generate the **Small.framework** in **$PODS_CONFIGURATION_BUILD_DIR/Small**. 

It's totally fine, but in **Small** way, I wanna to split the host application into bundles of subprojects, and all the subprojects requires the **Small.framework**. So there are tough jobs to set the **Framework Search Path** for each sub-projects.

An easy workaround is that, if we can generate the **Small.framework** just in **$PODS_CONFIGURATION_BUILD_DIR**, then every subprojects can find it.

Now the problem is how to make approach to this?

Following setting seems to _merge_ the `xcconfig` attribute but not **overwrite** it.

``` ruby
s.pod_target_xcconfig = { 'CONFIGURATION_BUILD_DIR' => '$PODS_CONFIGURATION_BUILD_DIR' }
```

The result is that the `CONFIGURATION_BUILD_DIR` becomes strange, something like:

```
/Users/galen/BUILD_DIR\ Users/galen/BUILD_DIR/Small/Small.framework 
```

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
