### ISSUE TITLE
Pod::Source::search_by_name doesn't work for Pod's with the '+' character

### ISSUE THREAD

**Issue by anuccio1** [CocoaPods/Core#349]
I ran search_by_name on the following pod: "XCTest+OHHTTPStubSuiteCleanUp"
got this error: 

[!] Unable to find a pod with name, author, summary, or descriptionmatching `XCTest+OHHTTPStubSuiteCleanUp`

My workaround was adding a '\' before the '+', and that worked. Nonetheless, this is a bug i believe.

**Comment by segiddins** [comment]
This is because `search_by_name` purposefully does a regular expression search
