### ISSUE TITLE
How to parse .podspec file ?

### ISSUE THREAD

**Issue by ShengQiangLiu** [CocoaPods/Core#353]
I need  create a Class to parse .podspec file ， Convert .podspec file to json file.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

However, [you should explore](https://guides.cocoapods.org/terminal/commands.html#pod_ipc_spec) `pod ipc spec`.

**Comment by ShengQiangLiu** [comment]
Hey . I know this  pod ipc spec.  I mean is create a new class to convert .podspec file to json file，It does not depend on CocoaPods-Core.
