### ISSUE TITLE
Suggestion to add dsl attribute umbrella_header_name.

### ISSUE THREAD

**Issue by myeyesareblind** [CocoaPods/Core#370]
Currently umbrella header is named automatically "#{label}-umbrella.h" for specs, which is not what you expect in apple-world (think <Foundation/Foundation.h>, <UIKit/UIKit.h>).
Most of popular libs explicitly create umbrella-headers that match library name by hand.

To automate this task I suggest to add umbrella_header_name attribute.

Would you accept PR for this functionality?

**Comment by segiddins** [comment]
If a module map is specified, the generated umbrella header is suppressed. But this relates more to CocoaPods/CocoaPods than the cocoapods-core gem (although the DSL does live in this repo)

**Comment by dnkoutso** [comment]
Closing as too old.
