### ISSUE TITLE
Podspec Guide should mention project header files

### ISSUE THREAD

**Issue by happycoloredbanana** [CocoaPods/Core#371]
(Opening the issue here because, if I understand it right, the Guide is generated from a file in this repo)

Currently, the [Podspec Guide](https://guides.cocoapods.org/syntax/podspec.html) provides description of ```public_header_files``` and ```private_header_files```. This creates an impression that there are two kinds of header files, and each header file in the pod's sources will end up being either public or private.

At the same time, actually there is a third type - header files that do not appear in neither of the above. For instance, in the generated project file, these files [will be added to the "Project" section of the "Headers" build phase](https://github.com/CocoaPods/CocoaPods/blob/8df7c49a783ab1661e8e1b532f7725a1604c2c39/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L403), unlike public and private header files.

Suggested fix: add a short note about the "project header" files, although there are no really such field in the podspec.

**Comment by dnkoutso** [comment]
@happycoloredbanana this should be easy to make a PR for, want to take a stab at it?

**Comment by happycoloredbanana** [comment]
I have no problem writing a couple of senences. But - I'd prefer if it'd be done by someone who understands the subject better than me.
