### ISSUE TITLE
Can't access my pod functions after installation

### ISSUE THREAD

**Issue by hemangshah** [CocoaPods/Core#378]
This is my [pod](https://cocoapods.org/pods/printer-logger) and this is [spec of that pod](https://github.com/CocoaPods/Specs/blob/master/Specs/e/0/0/printer-logger/1.0/printer-logger.podspec.json). 

Everything looks good so I have installed it on a sample project for the test.

I should able to import my project file name, that's "Printer". I can. But then I can't access to any of the functions of that file.

For example 

    Printer.log.success("Helllooo!!!!")

Please help!

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods/Core issues focused only on bug reports for the Core gem, and for upcoming feature requests. Which this doesn't look like.
