### ISSUE TITLE
Pod is not updated on CocoaPods

### ISSUE THREAD

**Issue by hemangshah** [CocoaPods/Core#379]
This is my [pod](https://cocoapods.org/pods/printer-logger), see the description below, it's not updated as per this [Read me](https://github.com/hemangshah/printer/blob/master/README.md) file on GitHub.

What am I doing wrong?

I have the latest release under "Release" on Github.com

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like. (This is related to ongoing issues detailed in the https://github.com/CocoaPods/cocoapods.org repo)
