### ISSUE TITLE
Improve fuzzy search for in the Pod::Source class

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/Core#42]
Support for fuzzy search has been already implemented in the `Source` class, although the `cocoapods` gem is not taking advantage of it yet. Currently the implementation is backed by the `fuzzy_match` gem which however appears to be geared to a slightly different use case that the one we are looking after.

One major limitation is that it doesn't take into account case to tokenize the names of the Pods. For example I consider convenient `ObjSug` to indicate `ObjectiveSugar`. This is very convenient for commands like `pod spec cat` and for printing a suggestion to the user including a similarly named Pod if one dependency in the Podfile could not be resolved.

**Comment by segiddins** [comment]
Closing as out of scope -- I think we have too many pods to really make this feasible anyways.
