### ISSUE TITLE
pod install fails when project name has smart quotes

### ISSUE THREAD

**Issue by sunnywalker** [CocoaPods/Core#437]
The pod file smart quote sanitizing is over-zealous and removes them even from the project name.

It also didn't warn about smart quotes on `pod init` -- only on `pod install`.

**Comment by akhilmantha** [comment]
You should turn off smart quotes in your text editor, this will solve the problem. Generally the CocoaPods is confused and displays an error. BTW if you are using any CI tools then you should probably update your pod file.

**Comment by sunnywalker** [comment]
As I mentioned in my bug report, the problem isn't with the text editor; it's when the project name itself has a curly quote (on purpose!). The `pod install` command fails because it's stripping *all* curly quotes, even when they are already legitimately quoted.

For example, this (arguably valid) Podfile fails to `pod install`.

```
platform :ios, '11.0'
target 'That’s Mine' do
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
end
```

**Comment by segiddins** [comment]
It’s a legit issue, but one I doubt we’ll be able to fix. For now, I’d recommend using `\uxxxx` to represent the smart quote in your podfile

**Comment by sunnywalker** [comment]
Thank you. I'll use `\u2019` for `’`. As also mentioned, it would also be nice to get the quotes warning on `pod init` and not just `pod install`.
