### ISSUE TITLE
[Linter] Refactor

### ISSUE THREAD

**Issue by Kapin** [CocoaPods/Core#48]
- [ ] The code style checker is having a fit about the linter growing to be too big. We either need to refactor some of the logic into another class or modify the code styler to allow for more additions.
- [ ] Explore the inclusion of validation related properties in the DSL attributes directly https://github.com/CocoaPods/Core/pull/50#commitcomment-4818973
- [x] Convert the mixing to a dedicated class - https://github.com/CocoaPods/Core/pull/50#commitcomment-4818973

--

- [x] Allow Attribute Names to be Passed Into Results (https://github.com/CocoaPods/Core/issues/127)
- [x] Linter results should keep attribute and message separate (https://github.com/CocoaPods/Core/issues/135)

_edit by @fabiopelosin_

**Comment by segiddins** [comment]
Closing this for now, but linter improvements are always welcome!
