### ISSUE TITLE
The sources order is lost for `pod ipc podfile`

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/Core#530]
I use the `pod ipc podfile` command to convert the podfile to yml, but I found that the sources lose the order.

Podfile
```
source 'a'
source 'z'
source 'b'
```

convert Podfile to Podfile.yml:
```
sources: 
  - a
  - b
  - z
```

**Comment by segiddins** [comment]
Tranferred issue to Core since that's what controls YAML serialization

**Comment by cltnschlosser** [comment]
> It is not easy to fix. The YAML generator will order all array data. It hard to keep the order for a array and reorder other array.

Do any of the arrays need to be sorted? If not then it will be easy to stop sorting. I don't know anything about this feature, just came across this issue.

**Comment by orta** [comment]
They do have to be sorted, the order is important when resolving dependencies

**Comment by cltnschlosser** [comment]
Order is important, but is there any reason that it's being sorted alphabetically currently? Or can this issue be resolved, by just removing the sorts in `yaml_helper`.
