### ISSUE TITLE
Allow specifying no default subspec

### ISSUE THREAD

**Issue by kylefleming** [CocoaPods/Core#584]
I would like to be able to have the ability specify in a podspec that the pod defaults to only the root spec and does not auto-include any of the subspecs as dependencies. (the equivalent of `s.default_subspecs = []`)

Given that you can make a pod with no subspecs, it seems logical that a pod should be able to specify that only the root spec should be included by default. This would allow pod authors to add optional functionality as subspecs without needing to create a dummy subspec to set as the `default_subspec`.

**Comment by dnkoutso** [comment]
Yes! Sounds like a good enhancements. Will mark it for 1.9.0 for now. Hopefully should be fairly easy to add.

**Comment by dnkoutso** [comment]
Seems like CocoaPods does:
```ruby
    def subspec_dependencies(platform = nil)
      specs = if default_subspecs.empty?
                subspecs.compact.reject(&:non_library_specification?)
              else
                default_subspecs.map do |subspec_name|
                  root.subspec_by_name("#{name}/#{subspec_name}")
                end
              end
      if platform
        specs = specs.select { |s| s.supported_on_platform?(platform) }
      end
      specs.map { |s| Dependency.new(s.name, version) }
    end
```

So setting `s.default_subspecs = []` is possible but has a different effect than the issue description here intends to accomplish. We might be better off introducing a `s.default_subspecs = :root` or maybe `s.default_subspecs = nil` which for some reason seems to me a bad idea :)

**Comment by dnkoutso** [comment]
At the very least we should ensure this change does not break the existing expected behavior unless the pod author explicitly updates their podspec to designate that all subspecs are "optional". I am also curious and want to ensure pod consumers are given a choice today which I think they do with `pod 'PodA', :subspecs => [...]` option.
