### ISSUE TITLE
[Feature Request] Support for development-pod-only script phase

### ISSUE THREAD

**Issue by kylefleming** [CocoaPods/Core#596]
I use the CocoaPods Development Pod feature when developing swift frameworks. I often want to include post-build script phases for development tasks like running swiftlint, but I'd like those phases to only run during development of the pod and not for production users of the pod.

In order to achieve this, I could imagine a `spec.script_phase` option for specifying that the phase is a development-only phase. This would specify that the phase is installed for the pod target when the pod is installed as a development pod and that the phase is absent otherwise.

In the example above of running swiftlint, this would allow the swiftlint script phase to remain in the podspec and would allow users of the the pod to build without the lint running, while also allowing development installs of the pod to build with the lint running.

The 2 workarounds I can think of at the moment are a) use a separate development podspec, and b) add the script phase programmatically in the development `Podfile`.

If there is already an existing CocoaPods convention for this kind of development workflow, I'm open to that as well.

**Comment by dnkoutso** [comment]
We can potentially add a `PODS_DEVELOPMENT_POD=1` build setting for pods we detect are development pods.

I imagine there are plenty of work arounds available here. Yuo have `$PODS_ROOT` so I think you can inspect from there in your script phase if the pod is local or not. I don't have the answer of the top of my mind but I am fairly certain you can accomplish this.

**Comment by kylefleming** [comment]
One consideration here is that with an environment variable, users of the pod will see this ominous messsage regardless of whether the script phase is a no-op or not:
```
[!] PodName has added 1 script phase. Please inspect before executing a build. See `https://guides.cocoapods.org/syntax/podspec.html#script_phases` for more information.
```

**Comment by amorde** [comment]
If you're using Ruby podspecs, you can sorta do this already by doing something like this:

```ruby
## in .podspec

unless ENV['ENABLE_DEVELOPMENT_SCRIPT'].nil?
  s.script_phase = ....
end


## in Podfile
ENV['ENABLE_DEVELOPMENT_SCRIPT'] = 'true'
```

what's nice about this is that it won't be published to trunk at all, unless you enable that environment variable when running `pod trunk push`

**Comment by dnkoutso** [comment]
@kylefleming is the comment from @amorde sufficient here? Seems like a good way to overcome this.

If so, please feel free to close the issue.

**Comment by kylefleming** [comment]
Yes, that workaround works fine for my use-case.

Would you consider removing the script phase warning for local pods? It seems like it would be less of a security issue if you're specifying a local path to the source code. This would allow local development on a pod without raising alarms for the pod developers.

**Comment by dnkoutso** [comment]
hmmm yeah we might be able to remove it for local pods.
