### ISSUE TITLE
Error parsing Podfile referencing script using Pod::UI

### ISSUE THREAD

**Issue by adamkirkton** [CocoaPods/Core#601]
React Native includes a [script](https://github.com/react-native-community/cli/blob/master/packages/platform-ios/native_modules.rb) in the Podfile to do some auto import work. This script uses the Pod::UI module to alert the user to issues. `Pod::Podfile.from_file` fails to parse a Podfile referencing this script. The error thrown is `uninitialized constant Pod::UI (NameError)`

I ran `Pod::Podfile.from_file` in a script using bundle exec with a Gemfile with `cocoapods-core` in it and I also tried with `cocoapods` in it in case there was some extra gem that was missing, but both had the same error.

I've attached the relevant files in a zip. If you download the files and run `bundle install && bundle exec ruby script.rb` you should be able to see the error.

[podfile-test.zip](https://github.com/CocoaPods/Core/files/3744009/podfile-test.zip)

**Comment by segiddins** [comment]
Do you have a `require 'cocoapods'` before you try to use code from CocoaPods?

**Comment by dnkoutso** [comment]
@adamkirkton @Gray-Wind is https://github.com/react-native-community/cli/pull/867 the correct fix here?

**Comment by Gray-Wind** [comment]
Version with those changes wasn't released yet.

**Comment by alloy** [comment]
Regardless, for the sake of keeping things tidy I think it’s fine to close this now 👍
