### ISSUE TITLE
spec.denpendency

### ISSUE THREAD

**Issue by LONGDDSF** [CocoaPods/Core#604]
How can I do this as demo at code.
@example
      #   spec.dependency 'AFNetworking', '~> 1.0', :configurations => ['Debug']

**Comment by dnkoutso** [comment]
This is only available on `master` branch. Use https://bundler.io/ to point to a sha and use this unreleased feature.

**Comment by LONGDDSF** [comment]
Ok,many thanks.
When can CocoaPods do this on release branch?
It is 1.8.4 version of CocoaPods on my iMac.
