### ISSUE TITLE
Ruby 2.7: URI.escape is obsolete

### ISSUE THREAD

**Issue by SlaunchaMan** [CocoaPods/Core#611]
Running the latest stable release fo CocoaPods on Ruby 2.7.0 produces the following warning:

```
/Users/jeff/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:326: warning: URI.escape is obsolete
```

This also happens on CocoaPods 1.9.0 beta 2:

```
/Users/jeff/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/cdn_source.rb:337: warning: URI.escape is obsolete
```

**Comment by frzng** [comment]
According to StdLib docs this became obsolete at 2.4.0. The [documentation](https://ruby-doc.org/stdlib-2.4.0/libdoc/uri/rdoc/URI/Escape.html#method-i-escape) says the following:

> This method is obsolete and should not be used. Instead, use CGI.escape, URI.www_form_encode or URI.www_form_encode_component depending on your specific use case.

**Comment by amorde** [comment]
I believe this was resolved in https://github.com/CocoaPods/Core/pull/613
