### ISSUE TITLE
warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by mateuszjablonski-slabs** [CocoaPods/Core#620]
When typing `pod install`, I get this bizzare warning multiple times:
`/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:337: warning: URI.escape is obsolete`
Any ideas what is wrong?

**Comment by dnkoutso** [comment]
Fixed here https://github.com/CocoaPods/Core/pull/613 haven't shipped yet.

**Comment by Thomazella** [comment]
@dnkoutso I suggest keeping it open to avoid duplicates. I was about to make one LOL

**Comment by FranklinYu** [comment]
Would we get notified when next release with #613 is out?

**Comment by dev4dev** [comment]
it's August and this is still a thing
![image](https://user-images.githubusercontent.com/722407/89454578-933ce180-d769-11ea-9399-78a035fd9c12.png)

**Comment by dnkoutso** [comment]
@dev4dev Please correct your tone and respect the people who work to support this project. 

Also 1.10.0.beta.1 has started that has fixed this issue http://blog.cocoapods.org/CocoaPods-1.10.0-beta/.

It seems you are using 1.9.3.

**Comment by dev4dev** [comment]
@dnkoutso I respect what people do, I did few small contribs to this project too, you can re-read my comment in a more calm way and it would be better 🤷🏻‍♂️

**Comment by LionelHoudelier** [comment]
Solved for me (was a ruby version problem with 2.7.1 and 2.7.2), solved with 2.6.6, described here: https://stackoverflow.com/a/64233692/14403548
