### ISSUE TITLE
CDNSource: delete a podspec if corruption is detected

### ISSUE THREAD

**Issue by igor-makarov** [CocoaPods/Core#653]
In response to https://github.com/CocoaPods/CocoaPods/issues/10118#issuecomment-703287282 I'm proposing to catch JSON parse exceptions in `CDNSource` and retry a file download.  
It's reasonable to assume that a JSON file that was successfully downloaded would be valid. Therefore, if there's an error, it is almost certainly due to network issues.

This undoubtedly contributes to "retry culture" proliferation but we don't control much of the content delivery network through which Specs are retrieved, and we have little insight into the frequency of occurrence of these issues.

**Comment by dnkoutso** [comment]
@igor-makarov still interested to do this for 1.11.0?

**Comment by igor-makarov** [comment]
@dnkoutso I'm not sure we need this, we've been having much less issues with the CDN, especially with undetected corruption.
