### ISSUE TITLE
pod spec lint warns about 'readme' and 'changelog' attributes

### ISSUE THREAD

**Issue by jrullman** [CocoaPods/Core#661]
Context: https://github.com/CocoaPods/cocoapods.org/issues/362, https://github.com/CocoaPods/cocoapods-metadata-service/issues/2

Recently there has not been a way for pods not hosted on GitHub to get a pod page on cocoapods.org. This has been remedied by updating the CocoaPods Metadata Service to look for 'readme' and 'changelog' attributes, which can hold URLs pointing to Markdown files. If present, the service fetches those files, converts them to HTML and stores them so that the pod page can render correctly.

Fix: https://github.com/CocoaPods/Core/pull/658

**Comment by dnkoutso** [comment]
#658 was merged so closing this for 1.11.0
