### ISSUE TITLE
Please I need clear explanation on how can I change my cocoapods of version 1.9.3 to 1.10.1 version. I have researched online and done update, uninstall and reinstall, yet it didn't work. 

### ISSUE THREAD

**Issue by samchidi2005** [CocoaPods/Core#684]
ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/ffi-1.15.0/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -I /Library/Ruby/Site/2.3.0 -r ./siteconf20210430-4933-141oiug.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/ffi-1.15.0 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/ffi-1.15.0/gem_make.out

**Comment by markph0204** [comment]
I always caution people using the System level Ruby...

Please see [this page](https://guides.cocoapods.org/using/getting-started.html#getting-started) for sudo-less install.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
