### ISSUE TITLE
Error with pod install: userinfo not supported.  [RFC3986]

### ISSUE THREAD

**Issue by Mebius973** [CocoaPods/Core#705]
* [X ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

I got the error: "userinfo not supported.  [RFC3986]"
My sources are like https://[USERNAME]:[PASSWORD]@MySpecRepo.com

## CocoaPods Environment

Happened with cocoapod 1.11.0
Worked like a charm with cocoapod 1.10.1

**Comment by dnkoutso** [comment]
This passes for me:

```ruby
          it 'test' do
            url = 'https://hello:world@MySpecRepo.com'
            @sources_manager.send(:name_for_url, url).
              should == 'myspecrepo'
          end
```

There is something specific to your URL and setup that causes the regex not to catch it.

**Comment by Mebius973** [comment]
Hello, you can use this repo to reproduce: https://gitlab.com/t2428/myapp
Type "pod install".
With pod 1.10.2 -> Everything is ok
With pod 1.11.0 -> userinfo not supported.  [RFC3986]

**Comment by dnkoutso** [comment]
let me see.

**Comment by dnkoutso** [comment]
Verified this works with #703 which will ship with 1.11.1 hopefully today.

**Comment by dnkoutso** [comment]
If you still see a problem I will re-open after 1.11.1 ships.

**Comment by dnkoutso** [comment]
Actually this may be have been a different issue which I think I got a fix. Follow along here https://github.com/CocoaPods/CocoaPods/issues/10941

**Comment by dnkoutso** [comment]
Actually will be fixed by https://github.com/CocoaPods/CocoaPods/pull/10942 instead.

**Comment by dnkoutso** [comment]
and PR https://github.com/CocoaPods/CocoaPods/pull/10942
